-- MySQL Script generated by MySQL Workbench
-- mié 23 jul 2014 07:41:42 ART
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lacomarca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lacomarca` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lacomarca` ;

-- -----------------------------------------------------
-- Table `lacomarca`.`tipo_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`tipo_documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(5) NULL,
  `detalle` VARCHAR(35) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`estados_civiles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`estados_civiles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`personas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nro_documento` VARCHAR(15) NULL,
  `apellido` VARCHAR(35) NULL,
  `nombre` VARCHAR(35) NULL,
  `nacimiento` VARCHAR(45) NULL,
  `sexo` VARCHAR(15) NULL,
  `id_tipo_documentos` INT NOT NULL,
  `id_estado_civil` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personas_tipodocumentos1_idx` (`id_tipo_documentos` ASC),
  INDEX `fk_personas_estadocivil1_idx` (`id_estado_civil` ASC),
  CONSTRAINT `fk_personas_tipodocumentos1`
    FOREIGN KEY (`id_tipo_documentos`)
    REFERENCES `lacomarca`.`tipo_documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personas_estadocivil1`
    FOREIGN KEY (`id_estado_civil`)
    REFERENCES `lacomarca`.`estados_civiles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`tipo_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`tipo_direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NULL,
  `nrocalle` VARCHAR(5) NULL,
  `escalera` VARCHAR(5) NULL,
  `piso` VARCHAR(5) NULL,
  `departamento` VARCHAR(5) NULL,
  `id_tipo_direcciones` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_direcciones_tipodirecciones1_idx` (`id_tipo_direcciones` ASC),
  CONSTRAINT `fk_direcciones_tipodirecciones1`
    FOREIGN KEY (`id_tipo_direcciones`)
    REFERENCES `lacomarca`.`tipo_direcciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`paises`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`paises` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `codigo_telefono` VARCHAR(10) NULL,
  `codigo_postal` VARCHAR(10) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`provincias` (
  `id` INT(2) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `id_paises` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_provincias_paises1_idx` (`id_paises` ASC),
  CONSTRAINT `fk_provincias_paises1`
    FOREIGN KEY (`id_paises`)
    REFERENCES `lacomarca`.`paises` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lacomarca`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`departamentos` (
  `id` INT(3) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `id_provincias` INT(2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departamentos_provincias1_idx` (`id_provincias` ASC),
  CONSTRAINT `fk_departamentos_provincias1`
    FOREIGN KEY (`id_provincias`)
    REFERENCES `lacomarca`.`provincias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lacomarca`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`localidades` (
  `id` INT(4) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `codigo_postal` VARCHAR(10) NULL,
  `codigo_telefono` VARCHAR(10) NULL,
  `id_departamentos` INT(3) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_localidades_departamentos1_idx` (`id_departamentos` ASC),
  CONSTRAINT `fk_localidades_departamentos1`
    FOREIGN KEY (`id_departamentos`)
    REFERENCES `lacomarca`.`departamentos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `lacomarca`.`domiclios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`domiclios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL DEFAULT NULL,
  `nro` INT NULL DEFAULT NULL,
  `escalera` VARCHAR(5) NULL DEFAULT NULL,
  `piso` VARCHAR(5) NULL DEFAULT NULL,
  `departamento` VARCHAR(5) NULL DEFAULT NULL,
  `localidades_id` INT(4) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_domiclios_localidades1_idx` (`localidades_id` ASC),
  CONSTRAINT `fk_domiclios_localidades1`
    FOREIGN KEY (`localidades_id`)
    REFERENCES `lacomarca`.`localidades` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`tipodocumentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`tipodocumentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(6) NULL DEFAULT NULL,
  `descripcion` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nrotarjeta` VARCHAR(45) NULL,
  `ingreso` DATE NULL,
  `id_personas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_personas1_idx` (`id_personas` ASC),
  CONSTRAINT `fk_clientes_personas1`
    FOREIGN KEY (`id_personas`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`direcciones_localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`direcciones_localidades` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_direcciones` INT NOT NULL,
  `id_localidades` INT(4) NOT NULL,
  INDEX `fk_direcciones_has_localidades_localidades1_idx` (`id_localidades` ASC),
  INDEX `fk_direcciones_has_localidades_direcciones1_idx` (`id_direcciones` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_direcciones_has_localidades_direcciones1`
    FOREIGN KEY (`id_direcciones`)
    REFERENCES `lacomarca`.`direcciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_direcciones_has_localidades_localidades1`
    FOREIGN KEY (`id_localidades`)
    REFERENCES `lacomarca`.`localidades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`contactos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`contactos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `telefono_fijo` VARCHAR(20) NULL,
  `telefono_movil` VARCHAR(20) NULL,
  `telefono_laboral` VARCHAR(20) NULL,
  `correo_electronico` VARCHAR(100) NULL,
  `pagina_web` VARCHAR(100) NULL,
  `id_personas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contactos_personas1_idx` (`id_personas` ASC),
  CONSTRAINT `fk_contactos_personas1`
    FOREIGN KEY (`id_personas`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`instituciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`instituciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `cuil` VARCHAR(15) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`laborales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`laborales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ocupacion` VARCHAR(45) NULL,
  `actividad` VARCHAR(45) NULL,
  `sueldo` DECIMAL NULL,
  `ingreso` DATE NULL,
  `id_instituciones` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_laborales_instituciones1_idx` (`id_instituciones` ASC),
  CONSTRAINT `fk_laborales_instituciones1`
    FOREIGN KEY (`id_instituciones`)
    REFERENCES `lacomarca`.`instituciones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`vinculaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`vinculaciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `sigla` VARCHAR(45) NULL,
  `detalle` VARCHAR(45) NULL,
  `id_laborales` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_vinculaciones_laborales1_idx` (`id_laborales` ASC),
  CONSTRAINT `fk_vinculaciones_laborales1`
    FOREIGN KEY (`id_laborales`)
    REFERENCES `lacomarca`.`laborales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`personas_laborales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`personas_laborales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_personas` INT NOT NULL,
  `id_laborales` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personas_has_laborales_laborales1_idx` (`id_laborales` ASC),
  INDEX `fk_personas_has_laborales_personas1_idx` (`id_personas` ASC),
  CONSTRAINT `fk_personas_has_laborales_personas1`
    FOREIGN KEY (`id_personas`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_personas_has_laborales_laborales1`
    FOREIGN KEY (`id_laborales`)
    REFERENCES `lacomarca`.`laborales` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`personas_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`personas_direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_personas` INT NOT NULL,
  `id_direcciones` INT NOT NULL,
  INDEX `fk_personas_has_direcciones_direcciones1_idx` (`id_direcciones` ASC),
  INDEX `fk_personas_has_direcciones_personas1_idx` (`id_personas` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_personas_has_direcciones_personas1`
    FOREIGN KEY (`id_personas`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_personas_has_direcciones_direcciones1`
    FOREIGN KEY (`id_direcciones`)
    REFERENCES `lacomarca`.`direcciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`tipo_familiares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`tipo_familiares` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`personas_personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`personas_personas` (
  `id_personas` INT NOT NULL,
  `id_familiar` INT NOT NULL,
  `id_tipofamiliares` INT NOT NULL,
  PRIMARY KEY (`id_personas`, `id_familiar`),
  INDEX `fk_personas_has_personas_personas2_idx` (`id_familiar` ASC),
  INDEX `fk_personas_has_personas_personas1_idx` (`id_personas` ASC),
  INDEX `fk_personas_has_personas_tipofamiliares1_idx` (`id_tipofamiliares` ASC),
  CONSTRAINT `fk_personas_has_personas_personas1`
    FOREIGN KEY (`id_personas`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_personas_has_personas_personas2`
    FOREIGN KEY (`id_familiar`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_personas_has_personas_tipofamiliares1`
    FOREIGN KEY (`id_tipofamiliares`)
    REFERENCES `lacomarca`.`tipo_familiares` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`clientes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nrotarjeta` VARCHAR(45) NULL,
  `ingreso` DATE NULL,
  `id_personas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_personas1_idx` (`id_personas` ASC),
  CONSTRAINT `fk_clientes_personas1`
    FOREIGN KEY (`id_personas`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`prestamos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `otorgado` DATE NULL,
  `plazos` INT NULL,
  `monto` DECIMAL NULL,
  `interes` DECIMAL NULL,
  `punitorios` DECIMAL NULL,
  `id_clientes` INT NOT NULL,
  `refinanciado` TEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_prestamos_clientes1_idx` (`id_clientes` ASC),
  CONSTRAINT `fk_prestamos_clientes1`
    FOREIGN KEY (`id_clientes`)
    REFERENCES `lacomarca`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`detalles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`detalles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nro_cuota` VARCHAR(45) NULL,
  `mes` VARCHAR(45) NULL,
  `vencimiento` VARCHAR(45) NULL,
  `capital` VARCHAR(45) NULL,
  `interes` VARCHAR(45) NULL,
  `iva` VARCHAR(45) NULL,
  `id_prestamos` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_detalles_prestamos1_idx` (`id_prestamos` ASC),
  CONSTRAINT `fk_detalles_prestamos1`
    FOREIGN KEY (`id_prestamos`)
    REFERENCES `lacomarca`.`prestamos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`garantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`garantes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(45) NULL,
  `id_personas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_garantes_personas1_idx` (`id_personas` ASC),
  CONSTRAINT `fk_garantes_personas1`
    FOREIGN KEY (`id_personas`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`garantes_prestamos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`garantes_prestamos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_garantes` INT NOT NULL,
  `id_prestamos` INT NOT NULL,
  INDEX `fk_garantes_has_prestamos_prestamos1_idx` (`id_prestamos` ASC),
  INDEX `fk_garantes_has_prestamos_garantes1_idx` (`id_garantes` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_garantes_has_prestamos_garantes1`
    FOREIGN KEY (`id_garantes`)
    REFERENCES `lacomarca`.`garantes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_garantes_has_prestamos_prestamos1`
    FOREIGN KEY (`id_prestamos`)
    REFERENCES `lacomarca`.`prestamos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(35) NULL,
  `contrasenia` VARCHAR(35) NULL,
  `tipo` VARCHAR(35) NULL,
  `id_personas` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_personas1_idx` (`id_personas` ASC),
  CONSTRAINT `fk_usuarios_personas1`
    FOREIGN KEY (`id_personas`)
    REFERENCES `lacomarca`.`personas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `detalle` VARCHAR(35) NULL,
  `id_usuarios` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_roles_usuarios1_idx` (`id_usuarios` ASC),
  CONSTRAINT `fk_roles_usuarios1`
    FOREIGN KEY (`id_usuarios`)
    REFERENCES `lacomarca`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `razon_social` VARCHAR(45) NULL,
  `cuit` VARCHAR(45) NULL,
  `calle` VARCHAR(45) NULL,
  `nro_calle` VARCHAR(45) NULL,
  `escalera` VARCHAR(45) NULL,
  `piso` VARCHAR(45) NULL,
  `departamento` VARCHAR(45) NULL,
  `telefono_fijo` VARCHAR(45) NULL,
  `telefono_celular` VARCHAR(45) NULL,
  `correo_electronico` VARCHAR(45) NULL,
  `pagina_web` VARCHAR(45) NULL,
  `incio_actividades` DATE NULL,
  `detalles` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lacomarca`.`instituciones_direcciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lacomarca`.`instituciones_direcciones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_instituciones` INT NOT NULL,
  `id_direcciones` INT NOT NULL,
  INDEX `fk_instituciones_has_direcciones_direcciones1_idx` (`id_direcciones` ASC),
  INDEX `fk_instituciones_has_direcciones_instituciones1_idx` (`id_instituciones` ASC),
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_instituciones_has_direcciones_instituciones1`
    FOREIGN KEY (`id_instituciones`)
    REFERENCES `lacomarca`.`instituciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_instituciones_has_direcciones_direcciones1`
    FOREIGN KEY (`id_direcciones`)
    REFERENCES `lacomarca`.`direcciones` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
